//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunmedyaAkademiPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAbout
    {
        public int AboutId { get; set; }
        public string Birthday { get; set; }
        public string Education { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
    }
}
